#!/usr/bin/env bash

COOKIEFILE=${1?No date or log inputted.}

subcommand=$1; shift
while getopts ":d:" flag
do
    case "${flag}" in
        d) DATE=${OPTARG};;
    esac
done

if [[ $DATE == "" ]]; then
    echo "No date or log inputted."
else
    javac ActiveCookie.java
    java ActiveCookie $COOKIEFILE $DATE
fi