#!/usr/bin/env bash

COOKIEFILE=${1?No log inputted.}

subcommand=$1; shift
while getopts ":d:" flag
do
    case "${flag}" in
        d) DATE=${OPTARG?No date inputted.};;
    esac
done

javac ActiveCookie.java
java ActiveCookie $COOKIEFILE $DATE